# Simple Linear Regression on Insurance DataSet

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as pltgit

In [63]:
"""
The dataset consists of age, sex, BMI(body mass index), children, 
smoker and region feature, which are independent and charge as a dependent feature.
We will predict individual medical costs billed by health insurance.
"""
df = pd.read_csv('insurance.csv')
print(df)

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]


In [64]:
print('\nNumber of rows and columns in the data set: ',df.shape)


Number of rows and columns in the data set:  (1338, 7)


In [65]:
df.head()

,age,sex,bmi,children,smoker,region,expenses
0,19,female,27.9,0,yes,southwest,16884.92
1,18,male,33.8,1,no,southeast,1725.55
2,28,male,33.0,3,no,southeast,4449.46
3,33,male,22.7,0,no,northwest,21984.47
4,32,male,28.9,0,no,northwest,3866.86


In [66]:
df.describe()

,age,bmi,children,expenses
count,1338.000000,1338.000000,1338.000000,1338.000000
mean,39.207025,30.665471,1.094918,13270.422414
std,14.049960,6.098382,1.205493,12110.011240
min,18.000000,16.000000,0.000000,1121.870000
25%,27.000000,26.300000,0.000000,4740.287500
50%,39.000000,30.400000,1.000000,9382.030000
75%,51.000000,34.700000,2.000000,16639.915000
max,64.000000,53.100000,5.000000,63770.430000


In [67]:
# Check for missing value
missing_values = df.isnull().sum()
print(missing_values)  # This will show the count of missing values in each column

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64


In [68]:
# ------ features and output (label) ------
input_df = df.drop(columns='expenses')
target_df = df.expenses

In [69]:
input_df

,age,sex,bmi,children,smoker,region
0,19,female,27.9,0,yes,southwest
1,18,male,33.8,1,no,southeast
2,28,male,33.0,3,no,southeast
3,33,male,22.7,0,no,northwest
4,32,male,28.9,0,no,northwest
...,...,...,...,...,...,...
1333,50,male,31.0,3,no,northwest
1334,18,female,31.9,0,no,northeast
1335,18,female,36.9,0,no,southeast
1336,21,female,25.8,0,no,southwest


In [70]:
target_df

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...   
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.95
1337    29141.36
Name: expenses, Length: 1338, dtype: float64

In [71]:
from sklearn.preprocessing import LabelEncoder

# Define the columns for encoding
columns_to_encode = ["sex", "smoker", "region"]  # Replace with your column names

# Create a LabelEncoder object
le = LabelEncoder()

# Loop through each column and encode
for col in columns_to_encode:
  input_df[col] = le.fit_transform(input_df[col])


In [72]:
input_df

,age,sex,bmi,children,smoker,region
0,19,0,27.9,0,1,3
1,18,1,33.8,1,0,2
2,28,1,33.0,3,0,2
3,33,1,22.7,0,0,1
4,32,1,28.9,0,0,1
...,...,...,...,...,...,...
1333,50,1,31.0,3,0,1
1334,18,0,31.9,0,0,0
1335,18,0,36.9,0,0,2
1336,21,0,25.8,0,0,3


In [73]:
from sklearn.preprocessing import MinMaxScaler

# Specify the column name for scaling
column_name = "expenses"  # Replace with the actual column name

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit the scaler on the column data (learn range)
scaler.fit(df[[column_name]])  # Double square brackets to select a DataFrame

# Transform the column data using the fitted scaler
scaled_data = scaler.transform(df[[column_name]])


In [74]:
target_df = scaled_data

In [75]:
target_df

array([[0.25161073],
       [0.00963598],
       [0.05311519],
       ...,
       [0.00810809],
       [0.01414366],
       [0.44724875]], shape=(1338, 1))

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(input_df, target_df, test_size=0.2, random_state=20)

In [77]:
X_test

,age,sex,bmi,children,smoker,region
698,56,1,33.7,0,0,1
520,50,0,27.4,0,0,0
1144,50,1,32.3,2,0,3
908,63,1,39.8,3,0,3
559,19,1,35.5,0,0,1
...,...,...,...,...,...,...
851,61,1,32.3,2,0,1
109,63,1,35.1,0,1,2
941,50,0,46.1,1,0,2
600,18,0,39.2,0,0,2


In [78]:
#For linear regression, Y=the value we want to predict
#X= all independent variables upon which Y depends. 
#3 steps for linear regression....
#Step 1: Create the instance of the model
#Step 2: .fit() to train the model or fit a linear model
#Step 3: .predict() to predict Y for given X values. 

In [79]:
from sklearn.linear_model import LinearRegression

#object
reg = LinearRegression()
#fit
reg.fit(X_train, Y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [80]:
prediction_test = reg.predict(X_test)

In [81]:
prediction_test

array([[ 0.19258687],
       [ 0.14249682],
       [ 0.16874043],
       [ 0.26996671],
       [ 0.05583164],
       [ 0.01680437],
       [ 0.01610805],
       [ 0.17216084],
       [ 0.59441419],
       [ 0.16238444],
       [ 0.24228155],
       [ 0.4441166 ],
       [ 0.03405751],
       [ 0.19215979],
       [ 0.45755453],
       [ 0.13640801],
       [ 0.49433625],
       [ 0.17793333],
       [ 0.03074942],
       [ 0.15972318],
       [ 0.60433825],
       [ 0.11343601],
       [ 0.1677746 ],
       [ 0.01922353],
       [ 0.18341015],
       [ 0.08130202],
       [ 0.50697874],
       [ 0.18656138],
       [ 0.4400924 ],
       [ 0.17455682],
       [ 0.14386894],
       [ 0.027059  ],
       [ 0.59476365],
       [ 0.59860627],
       [ 0.21801824],
       [ 0.09452994],
       [ 0.04442156],
       [-0.00244583],
       [ 0.49103   ],
       [ 0.39714886],
       [ 0.17789106],
       [ 0.2433805 ],
       [ 0.01184841],
       [ 0.00082175],
       [ 0.19559552],
       [ 0

In [82]:
from sklearn.metrics import mean_absolute_error 
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import median_absolute_error
import matplotlib.pyplot as plt

In [83]:
prediction_test = reg.predict(X_test)    
print(Y_test, prediction_test)
#----------------------------------------------------
#Calculating Mean Absolute Error
MAEValue = mean_absolute_error(Y_test, prediction_test, multioutput='uniform_average') # it can be raw_values
print('Mean Absolute Error Value is : ', MAEValue)

#----------------------------------------------------
#Calculating Mean Squared Error
MSEValue = mean_squared_error(Y_test, prediction_test, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

#----------------------------------------------------
#Calculating Median Squared Error
MdSEValue = median_absolute_error(Y_test, prediction_test)
print('Median Squared Error Value is : ', MdSEValue )

[[1.57296193e-01]
 [3.91624484e-01]
 [1.35813656e-01]
 [2.24238195e-01]
 [8.37305758e-03]
 [9.93797782e-03]
 [3.28012328e-02]
 [1.30277376e-01]
 [4.63906433e-01]
 [1.22004081e-01]
 [2.31295340e-01]
 [5.35531543e-01]
 [3.44461229e-02]
 [1.43083576e-01]
 [2.85743040e-01]
 [1.30260137e-01]
 [3.38550479e-01]
 [2.87679557e-01]
 [3.25558959e-02]
 [1.72538044e-01]
 [7.47122679e-01]
 [1.39400810e-01]
 [1.77195294e-01]
 [9.42336105e-03]
 [8.84995601e-02]
 [5.29364123e-02]
 [3.53127350e-01]
 [1.60670732e-01]
 [5.63072958e-01]
 [1.10158478e-01]
 [1.18089865e-01]
 [3.77097255e-02]
 [4.75993702e-01]
 [7.30541771e-01]
 [5.16374199e-01]
 [2.16941938e-02]
 [5.27868478e-02]
 [2.13194046e-02]
 [3.29608055e-01]
 [2.21628558e-01]
 [1.75706193e-01]
 [1.97114347e-01]
 [1.47460692e-02]
 [3.33115398e-02]
 [1.88416462e-01]
 [1.05429079e-01]
 [6.83034055e-02]
 [5.49465143e-02]
 [7.11721706e-01]
 [5.81681367e-02]
 [9.30082032e-02]
 [4.21590536e-01]
 [1.32890205e-01]
 [1.45408450e-01]
 [6.95334418e-02]
 [5.318237

In [84]:
#Y_test_original = scaler.inverse_transform(Y_test)
prediction_test_original = scaler.inverse_transform(prediction_test)

In [85]:
prediction_test_original

array([[13187.1597887 ],
       [10049.09033271],
       [11693.21493407],
       [18034.8953331 ],
       [ 4619.64159332],
       [ 2174.63928275],
       [ 2131.01583358],
       [11907.49879976],
       [38361.06287072],
       [11295.02152899],
       [16300.46019973],
       [28945.13519394],
       [ 3255.52366256],
       [13160.40427584],
       [29787.00250097],
       [ 9667.63544376],
       [32091.32446515],
       [12269.13661778],
       [ 3048.27708346],
       [11128.29718203],
       [38982.7912881 ],
       [ 8228.47264137],
       [11632.70696633],
       [ 2326.19646372],
       [12612.25163123],
       [ 6215.3241759 ],
       [32883.35828735],
       [12809.67189508],
       [28693.02506493],
       [12057.60346413],
       [10135.05163365],
       [ 2817.07719581],
       [38382.95606279],
       [38623.69083839],
       [14780.39858527],
       [ 7044.03433638],
       [ 3904.81702188],
       [  968.64197432],
       [31884.19238511],
       [26002.67413905],
