# Computer Vision with OpenCV

## Overview
This notebook documents my OpenCV learning journey, covering the fundamentals of computer vision, image processing, video analysis, and basic object detection through practical examples and exercises.

**Libraries:** OpenCV (`cv2`), NumPy, Matplotlib

In [ ]:
# import opencv library
import cv2 as cv
import os # library let you program communicate with you OS 
import numpy as np


5.0.0
c:\Users\LENOVO\anaconda\python.exe
5.0.0
c:\Users\LENOVO\anaconda\Lib\site-packages\cv2\__init__.py


In [3]:
import cv2

print("CascadeClassifier:", hasattr(cv2, "CascadeClassifier"))
print("VideoCapture:", hasattr(cv2, "VideoCapture"))
print("imread:", hasattr(cv2, "imread"))
print("imshow:", hasattr(cv2, "imshow"))
print("dnn:", hasattr(cv2, "dnn"))

CascadeClassifier: True
VideoCapture: True
imread: True
imshow: True
dnn: True


In [5]:

# read Photo
img=cv.imread('imgs/photo.jpg')
cv.imshow('image',img)
#print(img.shape)
print("pixels of Image matrix : ",img)
cv.waitKey(0)


pixels of Image matrix :  [[[ 91  43  79]
  [ 92  44  80]
  [ 93  45  81]
  ...
  [ 99  50  88]
  [ 98  49  87]
  [ 96  47  85]]

 [[ 93  45  81]
  [ 94  46  82]
  [ 94  46  82]
  ...
  [100  51  89]
  [ 98  49  87]
  [ 97  48  86]]

 [[ 96  48  84]
  [ 96  48  84]
  [ 97  49  85]
  ...
  [102  53  91]
  [101  52  90]
  [ 99  50  88]]

 ...

 [[170 129 120]
  [170 130 118]
  [171 130 121]
  ...
  [105  83  95]
  [107  84  98]
  [109  86 100]]

 [[169 131 119]
  [169 131 119]
  [170 132 120]
  ...
  [126 101 111]
  [127 102 112]
  [130 105 115]]

 [[171 133 121]
  [170 132 120]
  [171 133 121]
  ...
  [139 114 124]
  [141 116 126]
  [143 118 128]]]


-1

In [26]:
# change photo to gray one
imggray=cv.cvtColor(img,cv.COLOR_BGR2GRAY)
cv.imshow('image',img)
cv.imshow("gray image",imggray)
print(imggray.shape)
print(imggray.shape)
cv.waitKey(0)

[[ 59  60  61 ...  67  66  64]
 [ 61  62  62 ...  68  66  65]
 [ 64  64  65 ...  70  69  67]
 ...
 [131 131 132 ...  89  91  93]
 [132 132 133 ... 107 108 111]
 [134 133 134 ... 120 122 124]]
(243, 243)


-1

In [ ]:
# Gray video

cap=cv2.VideoCapture('videos/Download (1).mp4')

while True:

    st,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Video",gray)

    if cv2.waitKey(1) & 0xFF ==ord("q"): break

cap.release()
cv2.destroyAllWindows()


In [28]:
cap=cv2.VideoCapture(0)

while True:

    st,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Video",gray)

    if cv2.waitKey(1) & 0xFF ==ord("q"): break

cap.release()
cv2.destroyAllWindows()

In [4]:
#Blur Image
#this function take src , ksize (7,7) for every pixel look at neighborhood of 7*7 (it must be odd) -> 49  pixels  ,sigmax
imgBlur=cv.GaussianBlur(img,(7,7),0)
cv.imshow("Image",img)
cv.imshow("Blur Image ",imgBlur)
cv.waitKey(0)



-1

In [ ]:
#Canny Photo
#Canny is edge detector of objects in image , it shows only the objects edges
# it's role find the edges in the image -> "Where does the color or brightness change suddenly?
# it take 2 threshold 
# first one : ignore edges weaker than this 
# second one :  keep edges stronger than this 
imgCanny=cv.Canny(img,200,200)
cv.imshow("Image",img)
cv.imshow("Canny Image ",imgCanny)
cv.waitKey(0)



-1

In [29]:
# Resize Image
imgSize=img.shape # (y,x,colorChannels) (height,width,3)
print(imgSize)

#(150,150)->(width,heigth)
imgResized=cv.resize(img,(150,100))

cv.imshow("Image",img)
cv.imshow("Resized Image ",imgResized)

print(imgResized.shape)
cv.waitKey(0)



(243, 243, 3)
(100, 150, 3)


-1

In [21]:
# Create  Image from Scratch
# (height,width,color channals)
img=np.zeros((600,800,3),np.uint8) #datatype must by 8bit
img[:]=255,255,255
print(img.shape)
# Draw shapes on the Image
cv.line(img,(0,0),(img.shape[1],img.shape[0]),(255,0,0),2)
cv.rectangle(img,(50,50),(400,400),(0,255,0),2)
cv.circle(img,(300,300),200,(0,0,255),2)
cv.putText(img,"OpenCV",(350,30),cv.FONT_HERSHEY_COMPLEX,1,(255,0,0),2)
cv.imshow("img",img)


cv.waitKey(0)


(600, 800, 3)


-1

In [ ]:
# join Images

img1=cv.imread('imgs/photo.jpg')
img2=cv.imread('imgs/newimage.jpg')
img2=cv.resize(img2,(243,243))

# Horizontal stack heights must be equal 
imgH=np.hstack((img1,img2))
# Vectical stack width must be equal
imgV=np.vstack((img1,img2))
cv.imshow("img1",img1)
cv.imshow("img2",img2)
cv.imshow("imgh",imgH)
cv.imshow("imgv",imgV)
cv.waitKey(0)

-1

In [8]:
# Crop Image
# OpenCV stores an image as a 2D (or 3D for color) NumPy array.
# rows -> height , columns ->width
#img[rows,columns]
imgCropped=img[:,100:243]
cv.imshow("Image",img)
cv.imshow("Cropped Image ",imgCropped)
cv.waitKey(0)


-1

In [ ]:
# Detect car

carimg=cv.imread('imgs/redcar.jpg')
def nothing ():
    pass
# Create window
cv.namedWindow("TrackBars")
cv.resizeWindow("TrackBars", 640, 240)

# Create Trackbars
cv.createTrackbar("Hue Min", "TrackBars", 0, 179, nothing)
cv.createTrackbar("Hue Max", "TrackBars", 179, 179, nothing)

cv.createTrackbar("Sat Min", "TrackBars", 0, 255, nothing)
cv.createTrackbar("Sat Max", "TrackBars", 255, 255, nothing)

cv.createTrackbar("Val Min", "TrackBars", 0, 255, nothing)
cv.createTrackbar("Val Max", "TrackBars", 255, 255, nothing)

while True :
    #HSV describes  color, intensity, and brightness
    # now opencv can easily answer the qustion like is the pixel is red ?? from hue value 
    #Red = 255 Green = 0  Blue = 0  -> Hue(which color it is 0->179)= Red  Saturation = Strong color  Value= Bright
    # BGR affected by lighting while HSV the hue still indicate same color only birghtiness affected by lighting
    carimg_HSV=cv.cvtColor(carimg,cv.COLOR_BGR2HSV)
    # A mask is simply a black-and-white image
    # we Create Mask to ask each pixel Is your color between lower and upper? 
    # if answer yes make it white 255, it it no make it black 0

    # Get Trackbar values
    h_min = cv.getTrackbarPos("Hue Min", "TrackBars")
    h_max = cv.getTrackbarPos("Hue Max", "TrackBars")

    s_min = cv.getTrackbarPos("Sat Min", "TrackBars")
    s_max = cv.getTrackbarPos("Sat Max", "TrackBars")

    v_min = cv.getTrackbarPos("Val Min", "TrackBars")
    v_max = cv.getTrackbarPos("Val Max", "TrackBars")

    # Create lower and upper arrays
    lower = np.array([h_min, s_min, v_min])
    upper = np.array([h_max, s_max, v_max])



    imgMask=cv.inRange(carimg_HSV,lower,upper)
    imgRes=cv.bitwise_and(carimg,carimg,mask=imgMask) #actually applies the mask to the original image. is the mask white? yes copy the original pixel , no replace it with black

    cv.imshow("red car ",carimg)
    cv.imshow("red car HSV ",carimg_HSV)
    cv.imshow("Mask img of red car ",imgMask)
    cv.imshow("The Result Img ",imgRes)
    
    if cv.waitKey(1) & 0xFF == 27:
        break
cv.destroyAllWindows()    

In [23]:
# Detect Classic Shapes
import cv2

def getContours(img):
    # RETR_EXTERNAL ->find only the outer contour
    #CHAIN APPROX NONE ->keep every contour point
    # each contour is the list of all points lies on the edges each shape has list of points 
    contours,hierachy=cv2.findContours(img,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)


    for cnt in contours:
        area=cv2.contourArea(cnt)
        print("Area of Each Shape : ",area)

        # Ignore Small Objects 
        if area>500:

            # -1 -> draw the whole contour
            cv2.drawContours(imgcountour,cnt,-1,(0,0,0),8)
            peri=cv2.arcLength(cnt,True)
            approx=cv2.approxPolyDP(cnt,0.02*peri,True)# return only the Corner Points
            objectCor=len(approx)

            #Creates the smallest rectangle that surrounds the object
            # x-> x-cordinates of top left corner of the rectange , y-> y-cordinates of top left corner of the rectange 
            x,y,w,h=cv2.boundingRect(approx)# take corner points of each shape and create rectange pass through them

            if objectCor ==3 : objectType='Triangle'
            elif objectCor ==4:
                aspRatio=w/float(h)
                if aspRatio > 0.95 and aspRatio <1.05:objectType='Square'
                else : objectType="Rectangle"
            elif objectCor >4 : objectType='Circle'    
            else: objectType='None'

            # take first point and last point 
            cv2.rectangle(imgcountour,(x,y),(x+w,y+h),(0,255,0),5)
            cv2.putText(imgcountour,objectType,(x,y),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,0),2)


img=cv2.imread("imgs/Shapes.jpg")
# remove colors simplifies edge detection
grayimg=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# remove noise before edge detection 
blurimg=cv2.GaussianBlur(grayimg,(7,7),1)
# detect edges 
cannyimg=cv2.Canny(blurimg,200,200)
# Drawing on the copy of orginal image
imgcountour=img.copy()

getContours(cannyimg)
# cv2.imshow("Gray Image ",grayimg)
# cv2.imshow("image",img)
# cv2.imshow("blur Image ",blurimg)
# cv2.imshow("Cannying Image ",cannyimg)
cv2.imshow("contour img",imgcountour)
# Wait until a key is pressed 
cv2.waitKey(0)


Area of Each Shape :  15469.0
Area of Each Shape :  14905.0
Area of Each Shape :  15624.0
Area of Each Shape :  14155.5
Area of Each Shape :  8804.0
Area of Each Shape :  16802.0
Area of Each Shape :  13197.0
Area of Each Shape :  13331.0
Area of Each Shape :  14615.0


-1

In [ ]:
# read Videos
# Video is a group of  series images(frames) 

#This function creates an object that can capture frames from: A webcam A USB camera  A video file
# o default camera ,1 second camera , 2 third camera

cap=cv.VideoCapture('videos/Download (1).mp4')

while(True):
    status,frame=cap.read() # status will be true if there is anther frame to display
    if not status :
        break
    cv.imshow('video',frame)
    # every 1ms show 1 frame
    # i make it each 1 sec show 30 frame
    if cv.waitKey(33) & 0xFF ==ord("q"):break
   


cap.release()# close the video file and frees the resources    
cv.destroyAllWindows() # close every opencv window

In [ ]:
# open your Camera

cap=cv.VideoCapture(0) 

while(True):
    ret,frame=cap.read() # ret will be true if there is anther frame to display
    if not ret :
        break
    cv.imshow('video',frame)
    if cv.waitKey(1) & 0xFF == ord('q'):
     break

cap.release()# close the video file and frees the resources    
cv.destroyAllWindows() # close every opencv window



In [32]:
import cv2

print(cv2.__file__)
print(cv2.__version__)
print(hasattr(cv2, "CascadeClassifier"))

c:\Users\LENOVO\anaconda\Lib\site-packages\cv2\__init__.py
5.0.0
False


In [31]:
# Face Detection 
import cv2 

faceCascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
img=cv2.imread('imgs/girl.jpg')
imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=faceCascade.detectMultiScale(imgGray,1.1,4)

for (x,y,w,h)in faces:

    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

cv2.imshow("Face Detection", img)
cv2.waitKey(0)

AttributeError: module 'cv2' has no attribute 'CascadeClassifier'