# Computer Vision with OpenCV

## Overview
This notebook documents my OpenCV learning journey, covering the fundamentals of computer vision, image processing, video analysis, and basic object detection through practical examples and exercises.

**Libraries:** OpenCV (`cv2`), NumPy, Matplotlib

# Image Preprocessing

Image Preprocessing is the **first step** in Computer Vision.

Its goal is to **improve the quality of an image** before sending it to a Computer Vision model.

**Input:** Original Image  
**Output:** Enhanced Image (better for analysis)

```text
Original Image
      │
      ▼
Image Preprocessing
      │
      ▼
Enhanced Image
      │
      ▼
Computer Vision Model
```

---

## Main Image Preprocessing Techniques

<details>
<summary><strong>Image Segmentation</strong></summary>

Separates an image into meaningful regions or objects.

**Role:** Makes it easier to analyze specific objects.

</details>

<details>
<summary><strong>Data Augmentation</strong></summary>

Creates new training images by applying transformations such as flipping, rotating, or zooming.

**Role:** Increases dataset size and improves model accuracy.

</details>

<details>
<summary><strong>Image Color Model Conversion</strong></summary>

Converts an image from one color space to another (e.g., **BGR → RGB**, **Grayscale**, **HSV**).

**Role:** Uses the most suitable color representation for a task.

</details>

<details>
<summary><strong>Image Resizing</strong></summary>

Changes the image dimensions (width and height).

**Role:** Makes all images the required size for the model.

</details>

<details>
<summary><strong>Image Enhancement</strong></summary>

Improves image quality by reducing noise and increasing visibility.

### Filter Algorithms
- Remove noise.
- Smooth or sharpen the image.

### Contrast Adjusting Techniques
- Increase the difference between dark and bright pixels.
- Make image details easier to see.

</details>

---

## Summary

| Technique | Role |
|-----------|------|
| **Segmentation** | Separate objects from the image. |
| **Data Augmentation** | Create more training images. |
| **Color Model Conversion** | Change the image color space. |
| **Image Resizing** | Resize the image for the model. |
| **Image Enhancement** | Improve image quality. |
| → Filter Algorithms | Remove noise or sharpen details. |
| → Contrast Adjusting | Improve image brightness and contrast. |

In [37]:
# import opencv library
import cv2 as cv
import os # library let you program communicate with you OS 
import numpy as np


In [38]:
import cv2

print("CascadeClassifier:", hasattr(cv2, "CascadeClassifier"))
print("VideoCapture:", hasattr(cv2, "VideoCapture"))
print("imread:", hasattr(cv2, "imread"))
print("imshow:", hasattr(cv2, "imshow"))
print("dnn:", hasattr(cv2, "dnn"))

CascadeClassifier: True
VideoCapture: True
imread: True
imshow: True
dnn: True


# OpenCV Image Reading Flags

<details>
<summary><strong>cv2.IMREAD_COLOR</strong></summary>

- **Default** option.
- Loads the image as a **3-channel BGR** image.
- Ignores the **Alpha (transparency)** channel.
- **Shape:** `(Height, Width, 3)`

</details>

<details>
<summary><strong>cv2.IMREAD_GRAYSCALE</strong></summary>

- Converts the image to **grayscale**.
- Uses **1 channel** (brightness only).
- **Shape:** `(Height, Width)`

</details>

<details>
<summary><strong>cv2.IMREAD_ANYCOLOR</strong></summary>

- Loads the image in its **original color format**.
- Color image → **BGR**
- Grayscale image → **Grayscale**
- Does **not** force color conversion.

</details>

<details>
<summary><strong>cv2.IMREAD_UNCHANGED</strong></summary>

- Loads the image **without any modifications**.
- Preserves **all channels**, including **Alpha (transparency)**.
- Example: PNG with transparency → **BGRA (4 channels)**.

</details>

<details>
<summary><strong>cv2.IMREAD_ANYDEPTH</strong></summary>

- Preserves the image's **original bit depth**.
- Example:
  - **8-bit:** `0–255`
  - **16-bit:** `0–65535`
- Commonly used for **medical** and **scientific** images.

</details>

---

## Summary

| Flag | Channels | Alpha | Bit Depth |
|------|:--------:|:-----:|:---------:|
| `IMREAD_COLOR` | 3 (BGR) | ❌ | 8-bit |
| `IMREAD_GRAYSCALE` | 1 | ❌ | 8-bit |
| `IMREAD_ANYCOLOR` | Original | ❌ | 8-bit |
| `IMREAD_UNCHANGED` | Original | ✅ | Original |
| `IMREAD_ANYDEPTH` | Original | Depends | Original |

# Additional OpenCV Image Reading Flags

<details>
<summary><strong>cv2.IMREAD_ANYDEPTH | cv2.IMREAD_COLOR</strong></summary>

- Combines **ANYDEPTH** and **COLOR**.
- Loads the image in **BGR color**.
- Preserves the **original bit depth** (e.g., 8-bit, 16-bit).

</details>

<details>
<summary><strong>cv2.IMREAD_REDUCED_GRAYSCALE_2</strong></summary>

- Loads the image in **grayscale**.
- Reduces the image size to **1/2** of the original resolution.
- Example: `640×480 → 320×240`

</details>

<details>
<summary><strong>cv2.IMREAD_REDUCED_COLOR_2</strong></summary>

- Loads the image in **BGR color**.
- Reduces the image size to **1/2** of the original resolution.
- Example: `640×480 → 320×240`

</details>

<details>
<summary><strong>cv2.IMREAD_REDUCED_GRAYSCALE_4</strong></summary>

- Loads the image in **grayscale**.
- Reduces the image size to **1/4** of the original resolution.
- Example: `800×800 → 200×200`

</details>

<details>
<summary><strong>cv2.IMREAD_REDUCED_COLOR_4</strong></summary>

- Loads the image in **BGR color**.
- Reduces the image size to **1/4** of the original resolution.
- Example: `800×800 → 200×200`

</details>

<details>
<summary><strong>cv2.IMREAD_REDUCED_GRAYSCALE_8</strong></summary>

- Loads the image in **grayscale**.
- Reduces the image size to **1/8** of the original resolution.
- Example: `800×800 → 100×100`

</details>

<details>
<summary><strong>cv2.IMREAD_REDUCED_COLOR_8</strong></summary>

- Loads the image in **BGR color**.
- Reduces the image size to **1/8** of the original resolution.
- Example: `800×800 → 100×100`

</details>

---

## Summary

| Flag | Color | Resolution |
|------|:-----:|:----------:|
| `IMREAD_ANYDEPTH \| IMREAD_COLOR` | ✅ | Original |
| `IMREAD_REDUCED_GRAYSCALE_2` | ❌ | 1/2 |
| `IMREAD_REDUCED_COLOR_2` | ✅ | 1/2 |
| `IMREAD_REDUCED_GRAYSCALE_4` | ❌ | 1/4 |
| `IMREAD_REDUCED_COLOR_4` | ✅ | 1/4 |
| `IMREAD_REDUCED_GRAYSCALE_8` | ❌ | 1/8 |
| `IMREAD_REDUCED_COLOR_8` | ✅ | 1/8 |

In [44]:

#read Photo

img=cv2.imread('imgs/photo.jpg')
cv.imshow('image',img)
print(img.shape)
print("pixels of Image matrix : ",img)

cv.waitKey(0)


(243, 243, 3)
pixels of Image matrix :  [[[ 91  43  79]
  [ 92  44  80]
  [ 93  45  81]
  ...
  [ 99  50  88]
  [ 98  49  87]
  [ 96  47  85]]

 [[ 93  45  81]
  [ 94  46  82]
  [ 94  46  82]
  ...
  [100  51  89]
  [ 98  49  87]
  [ 97  48  86]]

 [[ 96  48  84]
  [ 96  48  84]
  [ 97  49  85]
  ...
  [102  53  91]
  [101  52  90]
  [ 99  50  88]]

 ...

 [[170 129 120]
  [170 130 118]
  [171 130 121]
  ...
  [105  83  95]
  [107  84  98]
  [109  86 100]]

 [[169 131 119]
  [169 131 119]
  [170 132 120]
  ...
  [126 101 111]
  [127 102 112]
  [130 105 115]]

 [[171 133 121]
  [170 132 120]
  [171 133 121]
  ...
  [139 114 124]
  [141 116 126]
  [143 118 128]]]


-1

In [41]:
# Image Writing

# cv2.imwrite("ResultedImg.jpg",img)
# cv2.imwrite(r'TheWholePath , and at the end of this path the name of the image you want to saveon')

In [45]:
# change photo to gray one
imggray=cv2.cvtColor(img,cv.COLOR_BGR2GRAY)
cv2.imshow('image',img)
cv2.imshow("gray image",imggray)
print(imggray.shape)
print(imggray.shape)
cv2.waitKey(0)

(243, 243)
(243, 243)


-1

In [ ]:
# Convert Grayscale to Binary

#cv2.threshold(image, threshold, newpixel, type)

# if i want to reverse and make what is black white and what is white blak use type cv2.THRESH_BINARY_INV
thresh,BlackAndWhiteImage=cv2.threshold(imggray,127,255,cv2.THRESH_BINARY)

cv2.imshow("BandW image",BlackAndWhiteImage)
cv2.waitKey(0)



-1

In [48]:
# Split and Merge

B,G,R=cv2.split(img)
cv2.imshow("blue",B)
cv2.imshow("Green",G)
cv2.imshow("Red",R)

merged=cv2.merge((B,G,R))
cv2.imshow("Merged ",merged)
cv2.waitKey(0)



-1

In [51]:
# BGR to HSV

HSV_img=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)


print(HSV_img.shape)
print("Hue : ",HSV_img[:,:,0])
print("Saturation : ",HSV_img[:,:,1])
print("Value : ",HSV_img[:,:,2])

cv2.imshow("HSV img",HSV_img)
cv2.waitKey(0)


(243, 243, 3)
Hue :  [[143 143 143 ... 143 143 143]
 [143 143 143 ... 143 143 143]
 [143 143 143 ... 143 143 143]
 ...
 [115 113 115 ... 136 138 138]
 [113 113 113 ... 132 132 132]
 [113 113 113 ... 132 132 132]]
Saturation :  [[135 133 132 ... 126 128 130]
 [132 130 130 ... 125 128 129]
 [128 128 126 ... 123 124 126]
 ...
 [ 75  78  75 ...  53  55  54]
 [ 75  75  75 ...  51  50  49]
 [ 75  75  75 ...  46  45  45]]
Value :  [[ 91  92  93 ...  99  98  96]
 [ 93  94  94 ... 100  98  97]
 [ 96  96  97 ... 102 101  99]
 ...
 [170 170 171 ... 105 107 109]
 [169 169 170 ... 126 127 130]
 [171 170 171 ... 139 141 143]]


-1

In [ ]:
# Gray video

cap=cv2.VideoCapture('videos/Download (1).mp4')

while True:

    st,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Video",gray)

    if cv2.waitKey(1) & 0xFF ==ord("q"): break

cap.release()
cv2.destroyAllWindows()


In [ ]:
cap=cv2.VideoCapture(0)

while True:

    st,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Video",gray)

    if cv2.waitKey(1) & 0xFF ==ord("q"): break

cap.release()
cv2.destroyAllWindows()

In [ ]:
#Blur Image
#this function take src , ksize (7,7) for every pixel look at neighborhood of 7*7 (it must be odd) -> 49  pixels  ,sigmax
# Delete gaussian noise 
imgBlur=cv.GaussianBlur(img,(7,7),0)
cv.imshow("Image",img)
cv.imshow("Blur Image ",imgBlur)
cv.waitKey(0)



-1

In [ ]:
import cv2

img=cv2.imread('imgs/photo.jpg')
cv2.imshow("Image ",img)

# make average kernal 
kernal=np.ones((7,7),np.int32)/49 # make each item in kernal = 1/49 to make sum of all kernal =1

# apply the lower pass kernal to the image  make the output image have same data type of input image
imgblur=cv2.filter2D(img,-1,kernel=kernal)
cv2.imshow("Img Blur ",imgblur)

#Average Filter 
blurimage=cv2.blur(img,(5,5))
cv2.imshow("Average img ",blurimage)

#Gaussian Blur
Gaussian=cv2.GaussianBlur(img,(7,7),0)
cv2.imshow("Gaussian Blurring ",Gaussian)

#Median blur
Medianblur=cv2.medianBlur(img,5)
cv2.imshow("Median blurring ",Medianblur)

#Bilateral Blur  -> edge perserving
bilateralblur=cv2.bilateralFilter(img,9,75,75)
cv2.imshow("Bilateral Blurring ",bilateralblur)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# Feature Extraction
import cv2

img=cv2.imread("imgs/photo.jpg")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

#apply sift detector
sift=cv2.SIFT_create()
kp=sift.detect(gray,None)

#Marking the keypoint on the img using circles
img1=cv2.drawKeypoints(gray,kp,img,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
kp,des=sift.detectAndCompute(gray,None)

cv2.imshow("Original image",gray)
cv2.imshow("Image with keypoints",img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# HISTOGRAM EQUALIZATION
import cv2
import numpy as np


# 0 shortcut to cv2.IMREAD_GRAYSCALE
img=cv2.imread('imgs/photo.jpg',0)
cv2.imshow("Image ",img)

equ=cv2.equalizeHist(img)
cv2.imshow("equ ",equ)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
#Canny Photo
#Canny is edge detector of objects in image , it shows only the objects edges
# it's role find the edges in the image -> "Where does the color or brightness change suddenly?
# it take 2 threshold 
# first one : ignore edges weaker than this 
# second one :  keep edges stronger than this 
imgCanny=cv.Canny(img,200,200)
cv.imshow("Image",img)
cv.imshow("Canny Image ",imgCanny)
cv.waitKey(0)



-1

In [55]:
# Resize Image
imgSize=img.shape # (y,x,colorChannels) (height,width,3)
print(imgSize)

#(150,150)->(width,heigth)
imgResized=cv.resize(img,(150,100))
#(0,0) -> calc new size automatically
imgResized=cv.resize(img,(0,0),fx=2,fy=2)

stretch_near=cv2.resize(img,(780,540),interpolation=cv2.INTER_NEAREST)
cv.imshow("Image",img)
cv.imshow("Resized Image ",imgResized)
cv.imshow("Stretched img ",stretch_near)

print(imgResized.shape)
cv.waitKey(0)



(243, 243, 3)
(486, 486, 3)


-1

In [ ]:
# Create  Image from Scratch
# (height,width,color channals)
img=np.zeros((600,800,3),np.uint8) #datatype must by 8bit
img[:]=255,255,255
print(img.shape)
# Draw shapes on the Image
cv.line(img,(0,0),(img.shape[1],img.shape[0]),(255,0,0),2)
cv.rectangle(img,(50,50),(400,400),(0,255,0),2)
cv.circle(img,(300,300),200,(0,0,255),2)
cv.putText(img,"OpenCV",(350,30),cv.FONT_HERSHEY_COMPLEX,1,(255,0,0),2)
cv.imshow("img",img)


cv.waitKey(0)


(600, 800, 3)


-1

In [ ]:
# join Images

img1=cv.imread('imgs/photo.jpg')
img2=cv.imread('imgs/newimage.jpg')
img2=cv.resize(img2,(243,243))

# Horizontal stack heights must be equal 
imgH=np.hstack((img1,img2))
# Vectical stack width must be equal
imgV=np.vstack((img1,img2))
cv.imshow("img1",img1)
cv.imshow("img2",img2)
cv.imshow("imgh",imgH)
cv.imshow("imgv",imgV)
cv.waitKey(0)

-1

In [ ]:
# Crop Image
# OpenCV stores an image as a 2D (or 3D for color) NumPy array.
# rows -> height , columns ->width
#img[rows,columns]
imgCropped=img[:,100:243]
cv.imshow("Image",img)
cv.imshow("Cropped Image ",imgCropped)
cv.waitKey(0)


-1

# Image Filtering

Image Filtering is an **Image Enhancement** technique used to improve image quality before Computer Vision.

**Goals:**
- Remove noise.
- Smooth the image.
- Sharpen details.
- Detect edges.

```text
Original Image
      │
      ▼
 Image Filter
      │
      ▼
Enhanced Image
```

---

## Types of Filters

<details>
<summary><strong>Low Pass Filter (Smoothing Filter)</strong></summary>

### Role
- Removes **noise**.
- Smooths the image by reducing sharp pixel changes.

### Advantages
- Removes random noise.
- Produces a smoother image.
- Useful before object detection or segmentation.

### Disadvantage
- Makes edges less sharp (blurring).

</details>

<details>
<summary><strong>High Pass Filter (Sharpening Filter)</strong></summary>

### Role
- Highlights **edges** and fine details.
- Keeps high-frequency information.

### Advantages
- Detects object boundaries.
- Sharpens image details.
- Useful for edge detection.

### Disadvantage
- Can also enhance noise.

</details>

---

# Common Blur (Low Pass) Filters

<details>
<summary><strong>1. Averaging Blur (Mean Filter)</strong></summary>

### How it works
- Replaces each pixel with the **average** of its neighboring pixels.

### OpenCV

```python
cv2.blur(img, (3,3))
```

### Advantages
- Very simple.
- Fast.
- Reduces small noise.

### Disadvantage
- Blurs edges significantly.

</details>

<details>
<summary><strong>2. Gaussian Blur</strong></summary>

### How it works
- Uses a **Gaussian (bell-shaped) kernel**.
- Gives **more weight to the center pixel** and less to distant pixels.

### OpenCV

```python
cv2.GaussianBlur(img, (5,5), 0)
```

### Advantages
- Better noise removal than averaging.
- Preserves edges better.
- Most commonly used blur filter.

### Disadvantage
- Still causes slight blurring.

</details>

<details>
<summary><strong>3. Median Blur</strong></summary>

### How it works
- Replaces the center pixel with the **median** value of neighboring pixels.

### OpenCV

```python
cv2.medianBlur(img, 5)
```

### Advantages
- Excellent for **Salt-and-Pepper noise**.
- Preserves edges better than averaging.

### Disadvantage
- Slower than averaging blur.

</details>

<details>
<summary><strong>4. Bilateral Filter</strong></summary>

### How it works
- Smooths the image **while preserving edges**.

### OpenCV

```python
cv2.bilateralFilter(img, 9, 75, 75)
```

### Advantages
- Removes noise.
- Keeps edges sharp.
- Produces high-quality results.

### Disadvantage
- Slowest blur filter.

</details>

---

# Quick Comparison

| Filter | Removes Noise | Preserves Edges | Speed | Best For |
|---------|:-------------:|:---------------:|:-----:|----------|
| Averaging Blur | ✅ | ❌ | ⭐⭐⭐⭐⭐ | Simple smoothing |
| Gaussian Blur | ✅✅ | ✅ | ⭐⭐⭐⭐ | General-purpose blur |
| Median Blur | ✅✅✅ | ✅✅ | ⭐⭐⭐ | Salt & Pepper noise |
| Bilateral Filter | ✅✅ | ✅✅✅ | ⭐ | High-quality smoothing |

---

# Easy Rules to Remember

- **Averaging Blur** → Average neighboring pixels.
- **Gaussian Blur** → Weighted average (center pixel is more important).
- **Median Blur** → Replace with the middle value (best for Salt & Pepper noise).
- **Bilateral Filter** → Remove noise **without blurring edges**.

---

# Summary

| Category | Purpose |
|----------|---------|
| **Low Pass Filter** | Remove noise and smooth the image. |
| **High Pass Filter** | Sharpen details and detect edges. |
| **Averaging Blur** | Fast smoothing using pixel average. |
| **Gaussian Blur** | Smooth image while preserving more details. |
| **Median Blur** | Best for Salt & Pepper noise. |
| **Bilateral Filter** | Smooth image while keeping edges sharp. |

In [7]:
# Image Filtring

import cv2

img=cv2.imread("imgs/photo.jpg")

# Averaging Filter (mean Filter) remove noise and edges
avgblur=cv2.blur(img,(3,3))
cv2.imshow("Mean Filter",avgblur)

#Gaussian Blurring remove gaussian noise
# if we give 0 to sigmax,  both sigma x , y will calculated from kernal size  
Gaussian=cv2.GaussianBlur(img,(7,7),0)
cv2.imshow("Gaussian filter ",Gaussian)

# remove salt and paper noise 
median=cv2.medianBlur(img,5)
cv2.imshow("median filter",median)

#Bilateral blure Remove noise while keep edges sharp
bilateral=cv2.bilateralFilter(img,9,75,75)
cv2.imshow("Bilateral filter",bilateral)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [10]:
# Histograms Equalization 
#Histogram Equalization is an image enhancement technique that improves the contrast of a grayscale image 
# by spreading pixel brightness values across the full range (0–255), making details easier to see
import cv2

img=cv2.imread('imgs/photo.jpg',0)
cv2.imshow("image",img)

equ=cv2.equalizeHist(img)
cv2.imshow("Equ",equ)
cv2.waitKey(0)

-1

# Edge Detection Methods

Edge Detection finds the **boundaries of objects** by detecting sudden changes in pixel intensity.

---

<details>
<summary><strong>1. Custom Kernel</strong></summary>

### Derivative
- Depends on the kernel you design.
- Can use **First** or **Second Derivative**.

### Role
- Create your own edge detector for a specific purpose.

### Advantages
- Fully customizable.
- Can detect specific patterns.

### Disadvantages
- Requires manual kernel design.

</details>

---

<details>
<summary><strong>2. Laplacian</strong></summary>

### Derivative
- **Second Derivative**

### Role
- Detects edges in **all directions** (horizontal, vertical, diagonal).

### OpenCV

```python
cv2.Laplacian(img, cv2.CV_64F)
```

### Advantages
- Detects all edge directions.
- Simple implementation.

### Disadvantages
- Very sensitive to noise.
- Usually Gaussian Blur is applied first.

</details>

---

<details>
<summary><strong>3. Sobel</strong></summary>

### Derivative
- **First Derivative**

### Role
- Detects edge direction.
- Uses two gradients:
  - **Gx** → Vertical edges
  - **Gy** → Horizontal edges

### OpenCV

```python
cv2.Sobel(img, cv2.CV_64F, 1, 0)  # Gx
cv2.Sobel(img, cv2.CV_64F, 0, 1)  # Gy
```

### Advantages
- Detects edge direction.
- Less sensitive to noise than Laplacian.
- Fast and widely used.

### Disadvantages
- Less accurate than Scharr for small kernels.

</details>

---

<details>
<summary><strong>4. Scharr</strong></summary>

### Derivative
- **First Derivative**

### Role
- Improved version of Sobel.
- Produces more accurate gradients.

### OpenCV

```python
cv2.Scharr(img, cv2.CV_64F, 1, 0)
```

### Advantages
- More accurate than Sobel.
- Better edge localization.

### Disadvantages
- Slightly slower than Sobel.

</details>

---

<details>
<summary><strong>5. Canny</strong></summary>

### Derivative
- Uses **First Derivative (Sobel)** internally.

### Pipeline
```text
Image
   │
   ▼
Gaussian Blur
   │
   ▼
Sobel Gradient
   │
   ▼
Non-Maximum Suppression
   │
   ▼
Double Threshold
   │
   ▼
Edge Tracking
```

### OpenCV

```python
cv2.Canny(img, 100, 200)
```

### Advantages
- High accuracy.
- Thin and clean edges.
- Removes most false edges.
- Most popular edge detector.

### Disadvantages
- Slower than Sobel.
- Requires choosing two thresholds.

</details>

---

# Quick Comparison

| Method | Derivative | Best For |
|---------|:----------:|----------|
| **Custom Kernel** | Depends | Custom edge detection |
| **Laplacian** | Second | Detecting edges in all directions |
| **Sobel** | First | Horizontal & vertical edge detection |
| **Scharr** | First | More accurate Sobel |
| **Canny** | First (Sobel) | High-quality edge detection |

---

## Easy Rules

```text
Custom Kernel
    ↓
Design your own filter

Laplacian
    ↓
Second Derivative
All edge directions

Sobel
    ↓
First Derivative
Horizontal & Vertical edges

Scharr
    ↓
Better Sobel
More accurate gradients

Canny
    ↓
Gaussian Blur
→ Sobel
→ Thin Edges
→ Threshold
→ Final Edges
```

In [16]:

import cv2
import numpy as np

# Custom Kernal
img = cv2.imread("imgs/photo.jpg", cv2.IMREAD_GRAYSCALE)

kernel = np.array([
    [-1, -1, -1],
    [-1,  8, -1],
    [-1, -1, -1]
])

edges = cv2.filter2D(img, -1, kernel)
cv2.imshow("Edges", edges)

# Laplacin Derivatives
laplacian = cv2.Laplacian(img, cv2.CV_64F)# cv_64F 64 floating point output prevent lossing negative edge info
cv2.imshow("Laplacian", laplacian)

# Sobel Derivatives
# Take first derivative in x direction to detect vertical edges
sobelX = cv2.Sobel(img, cv2.CV_64F, 1, 0)
# Take first derivative in Y direction to detect horizontal edges
sobelY = cv2.Sobel(img, cv2.CV_64F, 0, 1)
cv2.imshow("Sobel X", sobelX)
cv2.imshow("Sobel Y", sobelY)

# Scharr derivatives improved version from sobel
scharrX = cv2.Scharr(img, cv2.CV_64F, 1, 0)
scharrY = cv2.Scharr(img, cv2.CV_64F, 0, 1)
cv2.imshow("Scharr X", scharrX)
cv2.imshow("Scharr Y", scharrY)

edges = cv2.Canny(img, 100, 200)
cv2.imshow("Canny", edges)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
import cv2

img=cv2.imread("imgs/photo.jpg")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

# Create SIFT Detector object
sift=cv2.SIFT_create()
# Find Keypoints in the image search for corners , blobs 
# None -> search the entire image automatic 
kp=sift.detect(gray,None) # list of keypoints each kp cotain info like position , size , angle 

# cv2 draw circles on the copy of img and store the result in img1
img1=cv2.drawKeypoints(gray,kp,img,flags=cv2.DrawMatchesFlags_DRAW_RICH_KEYPOINTS)

# detect keypoint and descripte descriptor (fingerprint for each kp)to each keypoint
kp,des=sift.detectAndCompute(gray,None)
cv2.imshow("img1",img1)

cv2.waitKey(0)



-1

In [ ]:
# Detect car

import cv2 as cv
carimg=cv.imread('imgs/redcar.jpg')
def nothing ():
    pass
# Create window
cv.namedWindow("TrackBars")
cv.resizeWindow("TrackBars", 640, 240)

# Create Trackbars
cv.createTrackbar("Hue Min", "TrackBars", 0, 179, nothing)
cv.createTrackbar("Hue Max", "TrackBars", 179, 179, nothing)

cv.createTrackbar("Sat Min", "TrackBars", 0, 255, nothing)
cv.createTrackbar("Sat Max", "TrackBars", 255, 255, nothing)

cv.createTrackbar("Val Min", "TrackBars", 0, 255, nothing)
cv.createTrackbar("Val Max", "TrackBars", 255, 255, nothing)

while True :
    #HSV describes  color, intensity, and brightness
    # now opencv can easily answer the qustion like is the pixel is red ?? from hue value 
    #Red = 255 Green = 0  Blue = 0  -> Hue(which color it is 0->179)= Red  Saturation = Strong color  Value= Bright
    # BGR affected by lighting while HSV the hue still indicate same color only birghtiness affected by lighting
    carimg_HSV=cv.cvtColor(carimg,cv.COLOR_BGR2HSV)
    # A mask is simply a black-and-white image
    # we Create Mask to ask each pixel Is your color between lower and upper? 
    # if answer yes make it white 255, it it no make it black 0

    # Get Trackbar values
    h_min = cv.getTrackbarPos("Hue Min", "TrackBars")
    h_max = cv.getTrackbarPos("Hue Max", "TrackBars")

    s_min = cv.getTrackbarPos("Sat Min", "TrackBars")
    s_max = cv.getTrackbarPos("Sat Max", "TrackBars")

    v_min = cv.getTrackbarPos("Val Min", "TrackBars")
    v_max = cv.getTrackbarPos("Val Max", "TrackBars")

    # Create lower and upper arrays
    lower = np.array([h_min, s_min, v_min])
    upper = np.array([h_max, s_max, v_max])



    imgMask=cv.inRange(carimg_HSV,lower,upper)
    imgRes=cv.bitwise_and(carimg,carimg,mask=imgMask) #actually applies the mask to the original image. is the mask white? yes copy the original pixel , no replace it with black

    cv.imshow("red car ",carimg)
    cv.imshow("red car HSV ",carimg_HSV)
    cv.imshow("Mask img of red car ",imgMask)
    cv.imshow("The Result Img ",imgRes)
    
    if cv.waitKey(1) & 0xFF == 27:
        break
cv.destroyAllWindows()    

NameError: name 'cv' is not defined

In [ ]:
# Detect Classic Shapes
import cv2

def getContours(img):
    # RETR_EXTERNAL ->find only the outer contour
    #CHAIN APPROX NONE ->keep every contour point
    # each contour is the list of all points lies on the edges each shape has list of points 
    contours,hierachy=cv2.findContours(img,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)


    for cnt in contours:
        area=cv2.contourArea(cnt)
        print("Area of Each Shape : ",area)

        # Ignore Small Objects 
        if area>500:

            # -1 -> draw the whole contour
            cv2.drawContours(imgcountour,cnt,-1,(0,0,0),8)
            peri=cv2.arcLength(cnt,True)
            approx=cv2.approxPolyDP(cnt,0.02*peri,True)# return only the Corner Points
            objectCor=len(approx)

            #Creates the smallest rectangle that surrounds the object
            # x-> x-cordinates of top left corner of the rectange , y-> y-cordinates of top left corner of the rectange 
            x,y,w,h=cv2.boundingRect(approx)# take corner points of each shape and create rectange pass through them

            if objectCor ==3 : objectType='Triangle'
            elif objectCor ==4:
                aspRatio=w/float(h)
                if aspRatio > 0.95 and aspRatio <1.05:objectType='Square'
                else : objectType="Rectangle"
            elif objectCor >4 : objectType='Circle'    
            else: objectType='None'

            # take first point and last point 
            cv2.rectangle(imgcountour,(x,y),(x+w,y+h),(0,255,0),5)
            cv2.putText(imgcountour,objectType,(x,y),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,0),2)


img=cv2.imread("imgs/Shapes.jpg")
# remove colors simplifies edge detection
grayimg=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
# remove noise before edge detection 
blurimg=cv2.GaussianBlur(grayimg,(7,7),1)
# detect edges 
cannyimg=cv2.Canny(blurimg,200,200)
# Drawing on the copy of orginal image
imgcountour=img.copy()

getContours(cannyimg)
# cv2.imshow("Gray Image ",grayimg)
# cv2.imshow("image",img)
# cv2.imshow("blur Image ",blurimg)
# cv2.imshow("Cannying Image ",cannyimg)
cv2.imshow("contour img",imgcountour)
# Wait until a key is pressed 
cv2.waitKey(0)


Area of Each Shape :  15469.0
Area of Each Shape :  14905.0
Area of Each Shape :  15624.0
Area of Each Shape :  14155.5
Area of Each Shape :  8804.0
Area of Each Shape :  16802.0
Area of Each Shape :  13197.0
Area of Each Shape :  13331.0
Area of Each Shape :  14615.0


-1

In [ ]:
# read Videos
# Video is a group of  series images(frames) 

#This function creates an object that can capture frames from: A webcam A USB camera  A video file
# o default camera ,1 second camera , 2 third camera

cap=cv.VideoCapture('videos/Download (1).mp4')

while(True):
    status,frame=cap.read() # status will be true if there is anther frame to display
    if not status :
        break
    cv.imshow('video',frame)
    # every 1ms show 1 frame
    # i make it each 1 sec show 30 frame
    if cv.waitKey(33) & 0xFF ==ord("q"):break
   


cap.release()# close the video file and frees the resources    
cv.destroyAllWindows() # close every opencv window

In [ ]:
# open your Camera

cap=cv.VideoCapture(0) 

while(True):
    ret,frame=cap.read() # ret will be true if there is anther frame to display
    if not ret :
        break
    cv.imshow('video',frame)
    if cv.waitKey(1) & 0xFF == ord('q'):
     break

cap.release()# close the video file and frees the resources    
cv.destroyAllWindows() # close every opencv window



In [ ]:
import cv2

print(cv2.__file__)
print(cv2.__version__)
print(hasattr(cv2, "CascadeClassifier"))

c:\Users\LENOVO\anaconda\Lib\site-packages\cv2\__init__.py
5.0.0
False


In [ ]:
# Face Detection 
import cv2 

faceCascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
img=cv2.imread('imgs/girl.jpg')
imgGray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=faceCascade.detectMultiScale(imgGray,1.1,4)

for (x,y,w,h)in faces:

    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

cv2.imshow("Face Detection", img)
cv2.waitKey(0)

-1